### ISSUE TITLE
Unions unsupported?

### ISSUE THREAD

**Issue by thomasmarsh** [capnp-js/plugin#4]
I get this error with any capnp using unions:

```
% capnp compile -ojs union.capnp
Dust rendering error: Error: Template Not Found: [object Object],builders/union/bit
```

Here is a sample .capnp reproducing the issue:

```
@0xb7a9f7a90ff6bddd;

struct Test {
    union {
        a @0 :Bool;
        b @1 :Text;
    }
}
```

Is there any plan to support unions?

**Comment by popham** [comment]
I'm actually glad they're loudly broken.  I thought that default values for unions were silently broken.  This sounds preferable.

To your question: yes, unions will be supported.  (I've been privately migrating to an ES6 workflow that leverages [Flow](http://flowtype.org).  I would be migrating publicly, but I'm blocked by [Flow's missing Interface support](https://github.com/facebook/flow/issues/478#issuecomment-113314880).  Union support will follow on the heels of `interface` support within Flow.)

**Comment by couchand** [comment]
Any update on this?  I'd be glad to help.

**Comment by popham** [comment]
I've just pushed the beginnings of the new plugin. The generated code type-checks, but it's only a partial implementation of readers (builders should follow analogously very easily). To complete readers, I want to generate the `params` and `results` serializers from interfaces. See the non-`unit` directories at [capnp-js/builder-core/test](https://github.com/capnp-js/builder-core/tree/master/test) for handwritten implementations that I'm replicating with the plugin.
