### ISSUE TITLE
Code generation with syntax errors

### ISSUE THREAD

**Issue by sirudog** [capnp-js/plugin#6]
Hi,

I get syntax errors in the generated code based on your rtc-github-protocol project.
What I did:
1. Cloned the repo. I noticed that it comes with already generated code (in amd folder).
2. I cleaned the project: npm run clean
3. I wanted to regenerate the code, so I installed the plugin locally: npm install capnp-js-plugin. 
It worked, I got a few warnings but nothing serious:
![install_plugin](https://cloud.githubusercontent.com/assets/1550561/8953873/f0118750-35e1-11e5-914a-23323bf887f8.png)
4. Then I compiled the schemas: npm run compileMySchema
I got this error:
![compile_schema](https://cloud.githubusercontent.com/assets/1550561/8954003/f7ae73f0-35e2-11e5-92bb-cf76590c0f89.png)
5. And as a result the generated files have syntax error (I only checked user.capnp.d/readers.js, lines 21 - 25):
![generated_js](https://cloud.githubusercontent.com/assets/1550561/8954212/5812736c-35e4-11e5-9fe4-5d7afb8effce.png)

 I thought it is due to the unions, but in user.capnp, there are no unions, so even this fails on my pc.
I was using io.js v2.4.0 (npm v2.13.0) and then node v0.12.7 (npm v2.11.3), same problem.
Can you please help me in finding out what can go wrong here?

**Comment by sirudog** [comment]
Any help from anyone is much appreciated, even if it is just pointing to the right direction of finding the cause of this issue! I tried to debug the whole process, checking how dustjs renders js code, but it would take too much time, which I do not have in my current project, so currently we have to avoid using this otherwise awesome library.

**Comment by Pooja71** [comment]
Hi,
I was wondering if anyone found the solution to the problem of incorrect generation of the capnp.d files. I need to use it in my project and I am unable to find the root cause and use it. I would appreciate if anyone can give some inputs.

**Comment by sirudog** [comment]
Hi @Pooja71,

I am afraid this project is abandoned (about 2 years ago I got the info from the author that he was refactoring the project. No news ever since...) But there is hope! Please check out this rather new but very promising project: https://github.com/jdiaz5513/capnp-ts
I have not tried it yet, but I have plans to check it when they hit beta, or at least when the serialization part is fully implemented. Hope this helps!

**Comment by sirudog** [comment]
I guess I can close this issue after almost two years has passed without new info about this. There is a new project filling the gap if anyone is trying to use capnproto in js/ts: https://github.com/jdiaz5513/capnp-ts
Hope this helps
